name: "InstallNevstopPackage"
author: "NEVSTOP"
description: "CICD Action for installing package from nevstop-lab"
branding:
  icon: "anchor"
  color: "green"

inputs:
  LabVIEW_Version:
    description: "LabVIEW Version Used"
    required: false
    default: "2019"
  Architecture:
    description: "32bit/64bit Version of LabVIEW Used"
    required: false
    default: "x86"
  NEVSTOP-FTP-IP:
    description: "ip of FTP"
    required: false
    default: ""
  NEVSTOP-FTP-PORT:
    description: "PORT of FTP"
    required: false
    default: ""
  NEVSTOP-FTP-USER:
    description: "USER of FTP"
    required: false
    default: "anonymous"
  NEVSTOP-FTP-PASSWORDS:
    description: "PASSWORDS of FTP"
    required: true
    default: "anonymous"
  PackageName:
    description: "PackageName"
    required: true
    default: ""


runs:
  using: "composite"

  steps:
    - id: download-package
      uses: NEVSTOP-LAB/DownloadPackageFromNevstopFTP@main
      with:
        LabVIEW_Version: ${{ inputs.LabVIEW_Version }}
        Architecture: ${{ inputs.Architecture }}
        NEVSTOP-FTP-IP: ${{ inputs.NEVSTOP-FTP-IP }}
        NEVSTOP-FTP-PORT: ${{ inputs.NEVSTOP-FTP-PORT }}
        NEVSTOP-FTP-USER: ${{ inputs.NEVSTOP-FTP-USER }}
        NEVSTOP-FTP-PASSWORDS: ${{ inputs.NEVSTOP-FTP-PASSWORDS }}
        PackageName: ${{ inputs.PackageName }}

    - uses: NEVSTOP-LAB/vipm-InstallPackage@main
      with:
        LabVIEW_Version: 2017
        Package: ${{steps.download-package.outputs.vipPathName}}
