# This is a basic workflow to help you get started with Actions

name: InstallNevstopPackage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches:
      - main
    types: [closed]

  push:
    paths-ignore:
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  VIPM:
    # The type of runner that the job will run on
    runs-on: [self-hosted, lv2017]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: InstallNevstopPackage
        uses: NEVSTOP-LAB/InstallNevstopPackage@main
        with:
          LabVIEW_Version: 2017
          NEVSTOP-FTP-IP: ${{ secrets.VIPM_FTP_IP }}
          NEVSTOP-FTP-PORT: ${{ secrets.VIPM_FTP_PORT }}
          PackageName: LabVIEW-MassData-Smart-Ptr
          
      - name: InstallNevstopPackage2
        uses: NEVSTOP-LAB/InstallNevstopPackage@main
        with:
          LabVIEW_Version: 2017
          NEVSTOP-FTP-IP: ${{ secrets.VIPM_FTP_IP }}
          NEVSTOP-FTP-PORT: ${{ secrets.VIPM_FTP_PORT }}
          PackageName: NEVSTOP-Programming-Palette
